FROM python:3.6-alpine
LABEL maintainer="@juanrarodriguez18 <juanrarodriguez18@gmail.com>"

WORKDIR /usr/src/bot

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD [ "python", "./takeAdvantageOfYourFood/manage.py", "runserver", "0.0.0.0:8000" ]