# Generated by Django 2.1 on 2018-09-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ease_of_prep', models.CharField(max_length=100)),
                ('recipe_type', models.CharField(max_length=100)),
                ('prep_time', models.IntegerField(default=0)),
                ('photo', models.URLField()),
                ('ingredients_quantity', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Recipe'),
        ),
    ]
